/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/runners/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register a new runner
     * @description Creates a runner entry and returns a permanent authentication token.
     */
    post: operations["registerRunner"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/runners/{id}/heartbeat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Send a heartbeat
     * @description Signals the runner is alive and updates its remaining daily token quota. Must be called at least every 30 minutes to stay marked as active.
     */
    post: operations["heartbeat"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/issues/next": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the next pending issue
     * @description Returns the highest-scored pending issue from the queue. Returns 204 when the queue is empty.
     */
    get: operations["getNextIssue"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/issues/{id}/claim": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Claim an issue
     * @description Marks the issue as CLAIMED by the calling runner and starts the work timer.
     */
    post: operations["claimIssue"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/issues/{id}/done": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Report issue completion
     * @description Runner reports success or failure for a claimed issue. Failed issues may be retried up to the configured maximum (default: 3).
     */
    post: operations["reportDone"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get platform statistics
     * @description Returns aggregated counts for repositories, issues and runners across the platform.
     */
    get: operations["getStats"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/seed/repo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Seed a single repository
     * @description Fetches open issues from the given GitHub repository and adds qualifying ones to the scoring queue. Requires a valid X-Admin-Token header — admin-only endpoint.
     */
    post: operations["seedRepo"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/seed/default": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Seed default repositories
     * @description Seeds a curated list of well-known repositories (node, requests, scikit-learn) — useful for initial setup. Requires a valid X-Admin-Token header — admin-only endpoint.
     */
    post: operations["seedDefault"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    RegisterRequest: {
      /**
       * @description GitHub username or display name of the contributor
       * @example octocat
       */
      contributorName: string;
    };
    RegisterResponse: {
      /**
       * @description Generated UUID identifying this runner
       * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
       */
      runnerId?: string;
      /**
       * @description Permanent bearer token to pass as X-Runner-Token on every subsequent request
       * @example f1e2d3c4-b5a6-9870-fedc-ba9876543210
       */
      token?: string;
    };
    HeartbeatRequest: {
      /**
       * Format: int64
       * @description Claude API tokens remaining in the runner's daily quota
       * @example 50000
       */
      quotaRemainingToday: number;
    };
    DoneRequest: {
      /** @description Whether the runner succeeded in opening a pull request */
      success: boolean;
      /**
       * @description URL of the opened pull request
       * @example https://github.com/owner/repo/pull/42
       */
      prUrl?: string | null;
      /**
       * Format: int64
       * @description Total Claude tokens consumed during the work session
       * @example 12500
       */
      tokensUsed?: number | null;
      /** @description Human-readable error message when success is false */
      errorMessage?: string | null;
    };
    /**
     * @description Lifecycle state of an issue in the queue
     * @enum {string}
     */
    IssueStatus: "PENDING" | "CLAIMED" | "DONE" | "FAILED";
    /** @description A GitHub issue tracked by the hub */
    IssueDto: {
      /** @description Internal UUID of the issue */
      id?: string;
      /**
       * Format: int64
       * @description GitHub issue number
       */
      githubId?: number;
      /** @description Issue title */
      title?: string;
      /** @description Issue description (Markdown) */
      body?: string | null;
      /**
       * @description Direct URL to the GitHub issue
       * @example https://github.com/owner/repo/issues/42
       */
      githubUrl?: string;
      /**
       * @description GitHub URL of the repository containing this issue
       * @example https://github.com/owner/repo
       */
      repoUrl?: string;
      /**
       * @description Comma-separated list of GitHub labels
       * @example bug,good first issue
       */
      labels?: string;
      /**
       * Format: int32
       * @description Computed priority score (higher is better)
       * @example 85
       */
      score?: number;
      status?: components["schemas"]["IssueStatus"];
      /** @description UUID of the runner that claimed this issue */
      claimedBy?: string | null;
      /**
       * Format: date-time
       * @description Timestamp when the issue was claimed (ISO-8601)
       */
      claimedAt?: string | null;
      /**
       * Format: int32
       * @description Number of failed attempts so far
       * @example 0
       */
      retryCount?: number;
      /**
       * Format: date-time
       * @description Timestamp when the issue was ingested (ISO-8601)
       */
      createdAt?: string;
      /**
       * Format: date-time
       * @description Timestamp of the last status change (ISO-8601)
       */
      updatedAt?: string;
    };
    /** @description Aggregated platform statistics */
    StatsResponse: {
      /**
       * Format: int64
       * @example 42
       */
      totalRepos?: number;
      /**
       * Format: int64
       * @example 30
       */
      eligibleRepos?: number;
      /**
       * Format: int64
       * @example 1500
       */
      totalIssues?: number;
      /**
       * Format: int64
       * @example 200
       */
      pendingIssues?: number;
      /**
       * Format: int64
       * @example 10
       */
      claimedIssues?: number;
      /**
       * Format: int64
       * @example 800
       */
      doneIssues?: number;
      /**
       * Format: int64
       * @example 50
       */
      failedIssues?: number;
      /**
       * Format: int64
       * @example 850
       */
      totalPrsOpened?: number;
      /**
       * Format: int64
       * @example 5
       */
      activeRunners?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  registerRunner: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Runner registered successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegisterResponse"];
        };
      };
      /** @description Missing or invalid contributor name */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  heartbeat: {
    parameters: {
      query?: never;
      header: {
        "X-Runner-Token": string;
      };
      path: {
        /** @description Runner UUID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["HeartbeatRequest"];
      };
    };
    responses: {
      /** @description Heartbeat recorded */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid or missing runner token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Runner not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getNextIssue: {
    parameters: {
      query?: never;
      header: {
        "X-Runner-Token": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Next issue available */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueDto"];
        };
      };
      /** @description No pending issue in the queue */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid or missing runner token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  claimIssue: {
    parameters: {
      query?: never;
      header: {
        "X-Runner-Token": string;
      };
      path: {
        /** @description Issue UUID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Issue successfully claimed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueDto"];
        };
      };
      /** @description Invalid or missing runner token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Issue not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Issue already claimed by another runner */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  reportDone: {
    parameters: {
      query?: never;
      header: {
        "X-Runner-Token": string;
      };
      path: {
        /** @description Issue UUID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DoneRequest"];
      };
    };
    responses: {
      /** @description Report accepted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid request body */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid or missing runner token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Issue not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getStats: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current platform statistics */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatsResponse"];
        };
      };
    };
  };
  seedRepo: {
    parameters: {
      query: {
        /**
         * @description GitHub organisation or user login
         * @example nodejs
         */
        owner: string;
        /**
         * @description Repository name
         * @example node
         */
        name: string;
      };
      header: {
        /** @description Admin secret key (configured via ADMIN_KEY env var on the hub) */
        "X-Admin-Token": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Repository seeded successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Missing owner or name parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Missing or invalid X-Admin-Token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description GitHub API unreachable or rate-limited */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  seedDefault: {
    parameters: {
      query?: never;
      header: {
        /** @description Admin secret key (configured via ADMIN_KEY env var on the hub) */
        "X-Admin-Token": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default repositories seeded successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Missing or invalid X-Admin-Token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
