services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: pfg
      POSTGRES_USER: pfg
      POSTGRES_PASSWORD: pfg
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
