FROM node:22-bookworm-slim

WORKDIR /workspace

COPY pfg-runtime-config-core /pfg-runtime-config-core
COPY pfg-hub/package*.json ./
RUN npm install

COPY pfg-hub .

EXPOSE 8080

CMD ["sh", "-c", "npm install && npm run db:migrate && npm run dev"]
